version: "3.5"
services:
  db:
    image: mcr.microsoft.com/mssql/server
    hostname: 'sqlserver'
    environment:
      MSSQL_SA_PASSWORD: ${ERUPT_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
    ports:
      - 1433:1433

  project:
    depends_on:
      - db
    build:
      context: ./COMP4911Timesheets
      dockerfile: run.Dockerfile
    environment:
      ConnectionStrings_DefaultConnection: ${ConnectionStrings_DefaultConnection}
      Prod_Connection: ${Prod_Connection}
    ports:
      - 5000:80
    volumes:
      - ./COMP4911Timesheets:/app