version: "3.5"
services:
  db:
    image: mcr.microsoft.com/mssql/server
    hostname: 'sqlserver'
    environment:
      MSSQL_SA_PASSWORD: ${LOCAL_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433

  project:
    depends_on:
      - db
    build:
      context: .\COMP4911Timesheets
      dockerfile: run.Dockerfile
    environment:
      ASPNET_CONN: ${ASPNET_CONN}
    ports:
      - 5000:80
    volumes:
      - .\COMP4911Timesheets:/app